export const ADDTOCARD = "ADDTOCARD"
export const RMVPROD = "RMVPROD"
export const ADDTOTAL = "ADDTOTAL"
export const ADDQUANTITY="ADDQUANTITY"
export const REMOVETOTAL = "REMOVETOTAL"
export const REMOVEQUANTITY="REMOVEQUANTITY"
export const DETAILS="DETAILS"
export const  LIKE="Like"